@host=https://localhost:7068

POST {{host}}/authentication/register
Content-Type: application/json

{
  "firstName": "Dani",
  "lastName": "Vagyok",
  "email": "123@email.hu",
  "password": "asd123",
  "phoneNumber": "06-00-123-4567",
  "addresses": [
    {
      "zipCode": 3000,
      "city": "Hatvan",
      "street": "Robert Bosch út",
      "houseNumber": "1, 2. porta"
    }
  ]
}