@host=https://localhost:7068

POST {{host}}/authentication/register
Content-Type: application/json

{
    "firstName": "Dani",
    "lastName": "Vagyok",
    "email": "email@emmail.email",
    "password": "kekw"
}