@host=https://localhost:7068
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4IiwiZ2l2ZW5fbmFtZSI6IkRhbmkiLCJmYW1pbHlfbmFtZSI6IlZhZ3lvayIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFwcFVzZXIiLCJqdGkiOiI2MGI3NjZkZS05ZjlkLTQ4MDAtOWVmYi1lYWI4MDE2OGYzNjAiLCJleHAiOjE2Nzg4MDY3NjEsImlzcyI6IlRoZXNpc1Jlc3RhdXJhbnQiLCJhdWQiOiJUaGVzaXNSZXN0YXVyYW50In0.fQ2niVV6CgjH8waevGCCArIl5cIcmE4bW6D_G3C0E2s

GET {{host}}/food
Content-Type: application/json
Authorization: Bearer {{token}}

