@host=https://localhost:7068
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZ2l2ZW5fbmFtZSI6InN0cmluZyIsImZhbWlseV9uYW1lIjoic3RyaW5nIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJqdGkiOiJkMDIzZjljOS0wZWE0LTQ5NmYtOTI1Ny1lMTMwMDI1MGNjYTUiLCJleHAiOjE2Nzg3OTk2MTAsImlzcyI6IlRoZXNpc1Jlc3RhdXJhbnQiLCJhdWQiOiJUaGVzaXNSZXN0YXVyYW50In0.kiJVcANuqesRz34GE8s_nJIsG4dp6gcCCC8aiKCx-84

GET {{host}}/food
Content-Type: application/json
Authorization: Bearer {{token}}

