@host=https://localhost:7068
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6ImFkbWluIiwiZmFtaWx5X25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwianRpIjoiMTRlM2QxZTUtNGMxNy00OGYwLWJiOGYtZmM3NzE5NjczMzlmIiwiZXhwIjoxNjc5MzE4NTY3LCJpc3MiOiJUaGVzaXNSZXN0YXVyYW50IiwiYXVkIjoiVGhlc2lzUmVzdGF1cmFudCJ9.Va1mkrTfPYpfJ4MTEthX3za4dHpp6TgHawPLt0V_G3c
GET {{host}}/food/5
Content-Type: application/json
Authorization: Bearer {{token}}
